---

  - name: Download packages
    get_url: url={{item.url}}{{item.filename}} dest=/tmp
    with_items:
      packages

  - name: Install packages
    command: /usr/bin/dpkg -i /tmp/{{item.filename}}
    with_items:
      packages
