---

- name: Download packages via HTTP
  get_url:
    url: "{{item.url}}{{item.filename}}"
    dest: "{{deb_get_download_directory}}"
    force: no
  when: item.url is defined
  with_items:
    packages

- name: Download packages via rsync
  command: rsync {{item.rsync}}{{item.filename}} {{deb_get_download_directory}}
  when: item.rsync is defined
  with_items:
    packages

- name: Install packages
  apt: deb="{{deb_get_download_directory}}{{item.filename}}"
  with_items:
    packages
